dist: xenial
language: python
python:
  - "3.8"
install:
  - sudo apt update
  - sudo apt install python3-dev python3-pip
  - pip3 install --upgrade pip
  - pip3 install --upgrade tensorflow
script:
  - python3 convert.py
